### ISSUE TITLE
Install failure on R < 3.0.0. Simple to fix.

### ISSUE THREAD

**Issue by mvkorpel** [HenrikBengtsson/matrixStats#79]
The current version of matrixStats officially requires `R >= 2.12.0`. However, the real requirement seems to be `R >= 3.0.0`.

The compiler error I see is the following:

    In file included from validateIndices.c:7:0:
    utils.h:9:17: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
     static R_INLINE void assertArgVector(SEXP x, int type, char *xlabel) {

and a bunch of similar errors. I get the same errors on R 2.12.0, 2.15.2 and 2.15.3. Installing the package works on R 3.0.0 and later (also tested on fairly recent development and patched versions).

I traced the error to a missing definition of `R_INLINE` during compilation. The symbol is defined in `Rconfig.h` (part of R). On R 3.0.0 and later, including `Rinternals.h` (as done in `utils.h` of matrixStats) also brings in `Rconfig.h`. However, when looking at the header files included with R 2.15.3, I found no path from `Rinternals.h` to `Rconfig.h`. It appears that the corresponding change to `Rinternals.h` was made in SVN revision 60891 of the R development source. The first release after that, ignoring changes to patchlevel, is R 3.0.0.

[Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) hints that the standard way of getting a definition for `R_INLINE` is `#include <R.h>`, and indeed, adding that to `utils.h` seems to fix the issue, i.e. the package can be installed on R 2.12.0.

**Comment by HenrikBengtsson** [comment]
Thanks a bunch Mikko.  I agree with your troubleshooting.  My guess is that we broken the backward compatibility in matrixStats 0.50.0.

I've incorporated this fix and verified with R 2.12.2 on Linux (didn't have 2.12.0 installed, but it seems you checked with that version).

**Comment by HenrikBengtsson** [comment]
Forgot to say I've incorporated it into the `develop` branch, which can be installed as:
```r
source("http://callr.org/install#HenrikBengtsson/matrixStats@develop")
```

**Comment by mvkorpel** [comment]
Thanks for the very quick fix. I cloned the repository and built the latest development version of your package. I can verify that installing the package now works in R 2.12.0. Tested on Ubuntu 14.04 LTS. R was compiled from source with no other customization than the install path.

**Comment by HenrikBengtsson** [comment]
Great.
